App\Entity\Location: 

  properties:
    latitude:
     - Range:
         min: -90
         max: 90
         groups: [edit]
     - NotBlank: 
        groups: [edit]
    longitude:
     - Range:
         min: -90
         max: 90
         groups: [edit]
     - NotBlank: 
        groups: [edit]


    
